CREATE TABLE  CONDOMINIO_ECOVILA (
    ID  NUMBER PRIMARY KEY,
    NOME VARCHAR(100) ,
    BLOCO VARCHAR(2),
    APARTAMENTO VARCHAR(3),
    TEMVEICULO VARCHAR(2)
);
/
DROP PROCEDURE PRD_INSERIR_MORADOR;
CREATE PROCEDURE PRC_INSERIR_MORADOR(
P_ID NUMBER,
P_NOME VARCHAR2,
P_BLOCO VARCHAR2,
P_AP VARCHAR2,
P_VEICULO VARCHAR2
)
IS
BEGIN
IF (P_ID IS NULL OR P_NOME IS NULL OR P_BLOCO IS NULL OR P_AP IS NULL )THEN
DBMS_OUTPUT.PUT_LINE('PARA ADICIONAR  UM REGISTRO NO BANCO DE DADOS E NECESSARIO PASSAR UM VALOR VALIDO.');
END IF;

IF (P_VEICULO IS  NULL)THEN
INSERT  INTO  CONDOMINIO_ECOVILA (ID,NOME,BLOCO,APARTAMENTO) VALUES (P_ID,P_NOME,P_BLOCO,P_AP);
DBMS_OUTPUT.PUT_LINE('INSERT REALIZADO SEM OS DADOS DO VEICULO');
END IF;

IF (P_ID IS NOT NULL AND P_NOME IS NOT NULL AND P_BLOCO IS NOT NULL) THEN
INSERT  INTO  CONDOMINIO_ECOVILA (ID,NOME,BLOCO,APARTAMENTO,TEMVEICULO) VALUES (P_ID,P_NOME,P_BLOCO,P_AP,P_VEICULO);
DBMS_OUTPUT.PUT_LINE('REGISTRO INSERIDO COM SUCESSO!');
END IF;
END;