DROP FUNCTION  FNC_CONSULTA_MORADOR_BY_NAME;
SELECT FNC_CONSULTA_MORADOR_BY_ID(1) FROM DUAL;
SELECT FNC_CONSULTA_MORADOR_BY_NAME('MAXWELL') FROM DUAL;
ALTER TABLE CONDOMINIO_ECOVILA MODIFY  TEMVEICULO VARCHAR(3);
SELECT * FROM VMORADORES_ECOVILA;